apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
  labels:
    app: udagram-feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feed-api
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      containers:
      - name: udagram-feed-api
        image: swissvic/udagram-feed-api
        ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port:8080