apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
  labels:
    service: udagram-feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-feed-api
  template:
    metadata:
      labels:
        service: udagram-feed-api
    spec:
      containers:
      - name: udagram-feed-api
        image: swissvic/udagram-feed-api
        env:
        - name: POSTGRES_USERNAME
          value: victordev
        - name: POSTGRES_PASSWORD
          value: Password12
        - name: POSTGRES_DATABASE
          value: udagramvictordev
        - name: POSTGRES_HOST
          value: udagramvictordev.cvizerg6wgrh.us-west-2.rds.amazonaws.com
        - name: AWS_REGION
          value: eu-west-2
        - name: AWS_PROFILE
          value: default
        - name: AWS_MEDIA_BUCKET
          value: awsclouddeveloper-dev
        - name: PORT
          value: '8080'
        - name: FE_URL
          value: http://a140fe6198c914d9da47684c99510d5e-1335044447.eu-west-2.elb.amazonaws.com:8100
        ports:
        - containerPort: 8080